version: '3'

services:

  redis:
    container_name: "fib_api-redis"
    image: redis:6.2.6
    ports:
      - "6379:6379"

  fib_api:
    container_name: "fib_api-app"
    build: .
    command: python app.py
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - redis
