ENV_NAME_DEPLOY_TYPE = 'FIB_API_DEPLOY_TYPE'
ENV_NAME_HOST = 'FIB_API_HOST'
ENV_NAME_PORT = 'FIB_API_PORT'

ENV_VALUE_DEV = 'DEV'
ENV_VALUE_PROD = 'PROD'

DEFAULT_HOST = '127.0.0.1'
DEFAULT_PORT = 5000
